Repository dashpay/dash-wallet, pull requests merged in 2020-01, with the labels that each got.

#284 NMA-192 PIN | Lock Timer
  common/src/main/java/org/dash/wallet/common/Configuration.java
  wallet/res/menu/wallet_options.xml
  wallet/src/de/schildbach/wallet/ActivitiesTracker.java
  wallet/src/de/schildbach/wallet/AutoLogout.java
  wallet/src/de/schildbach/wallet/WalletApplication.java
  wallet/src/de/schildbach/wallet/data/WalletLock.java
  wallet/src/de/schildbach/wallet/ui/BaseMenuActivity.kt
  wallet/src/de/schildbach/wallet/ui/CanAutoLockGuard.java
  wallet/src/de/schildbach/wallet/ui/CheckPinDialog.kt
  wallet/src/de/schildbach/wallet/ui/EncryptKeysDialogFragment.java
  wallet/src/de/schildbach/wallet/ui/ExchangeRatesFragment.java
  wallet/src/de/schildbach/wallet/ui/LockScreenActivity.kt
  wallet/src/de/schildbach/wallet/ui/SecurityActivity.kt
  wallet/src/de/schildbach/wallet/ui/SessionActivity.kt
  wallet/src/de/schildbach/wallet/ui/SetPinActivity.kt
  wallet/src/de/schildbach/wallet/ui/UnlockWalletDialogFragment.java
  wallet/src/de/schildbach/wallet/ui/VerifySeedActivity.kt
  wallet/src/de/schildbach/wallet/ui/WalletActivity.java
  wallet/src/de/schildbach/wallet/ui/WalletBalanceToolbarFragment.java
  wallet/src/de/schildbach/wallet/ui/preference/PreferenceActivity.java
Labels: REDESIGN

#288 Spending Confirmation
  wallet/src/de/schildbach/wallet/ui/send/SendCoinsFragment.java
Labels: REDESIGN

#289 Redesign recovery phrase error fix [NMA-284 #2]
  wallet/src/de/schildbach/wallet/ui/RestoreWalletFromSeedViewModel.kt
Labels: REDESIGN

#286 Fingerprint Toggle in Security screen
  wallet/res/layout/activity_security.xml
  wallet/res/values/strings.xml
  wallet/src/de/schildbach/wallet/ui/SecurityActivity.kt
Labels: REDESIGN

#297 Fix Localbitcoins fallback strategy
  common/build.gradle
  wallet/build.gradle
  wallet/src/de/schildbach/wallet/Constants.java
  wallet/src/de/schildbach/wallet/data/DynamicFeeLoader.java
  wallet/src/de/schildbach/wallet/offline/DirectPaymentTask.java
  wallet/src/de/schildbach/wallet/rates/LocalBitcoinsClient.java
  wallet/src/de/schildbach/wallet/rates/LocalBitcoinsRate.java
  wallet/src/de/schildbach/wallet/rates/LocalBitcoinsResponse.java
  wallet/src/de/schildbach/wallet/rates/RetrofitClient.java
  wallet/src/de/schildbach/wallet/ui/send/RequestPaymentRequestTask.java
  wallet/src/de/schildbach/wallet/ui/send/RequestWalletBalanceTask.java
  wallet/src/de/schildbach/wallet/util/HttpGetThread.java
Labels: bug

#304 PIN finger print alignments to iOS [NMA-320]
  common/src/main/java/org/dash/wallet/common/Configuration.java
  wallet/src/de/schildbach/wallet/ui/CheckPinDialog.kt
  wallet/src/de/schildbach/wallet/ui/SecurityActivity.kt
  wallet/src/de/schildbach/wallet/ui/SetPinActivity.kt
Labels: REDESIGN, bug
